name: Buildwith-IONOS

on: [push]

jobs:
  build-with-ionos:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get Ionos Project data
        uses: buildwith-ionos/retrieve-project-info-action@v0.1.2
        id: project
        with:
          project: 3be79de3-5db5-49a5-9c86-13c09bd9da32
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: Setup Node.js 12.16.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: Build Node project
        run: yarn build
        env:
          SITE_URL: ${{ steps.project.outputs.site-url }}
          CI: true
      - name: Deploy to IONOS
        uses: buildwith-ionos/deploy-to-ionos-action@v0.1.2
        with:
          dist-folder: dist
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: 3be79de3-5db5-49a5-9c86-13c09bd9da32
          remote-host: ${{ steps.project.outputs.remote-host }}
