name: Publish page

on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install & build
      run: |
        yarn install --frozen-lockfile
        yarn build
        ls -la
        echo ${{ secrets.FTP_HOST }} ${{ secrets.FTP_USER }}
    - name: Publish dist folder
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftps://home160254503.1and1-data.host:21/buildwith-ionos
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: "dist"
        git-ftp-args: --insecure